### ISSUE TITLE
don't always use ssl context

### ISSUE THREAD

**Issue by leohemsted** [alphagov/notifications-java-client#115]
in their development environment, pay want to be able to stub out notify - the easiest way is to have a mock notify service. but they can't give a `http` URL - because we set up a default ssl context, it won't work or something. They'd have to set up their stub service with https which is a bit extreme. If someone passes in an HTTP url, we shouldn't set up the ssl context I guess. I'm not too sure how java works.

@mrlumbu or @simad can probably provide more details

**Comment by darrengreaves** [comment]
We use a `http` stub locally and it works fine (using the Java API).
Happy to discuss any details on Slack or here if anyone wants to know more.
