### ISSUE TITLE
Support Java 8 Datetime API

### ISSUE THREAD

**Issue by Chessray** [alphagov/notifications-java-client#61]
The Java client is already packed up for Java 8, so would you consider supporting the Java 8 Datetime API instead of or in addition to Joda Time?

**Comment by idavidmcdonald** [comment]
Hey @Chessray, sorry for the outrageously late getting back to you on this issue. I'm just doing something housekeeping on our open issues. Does this issue still stand and is still something you'd like to see changed?

**Comment by Chessray** [comment]
Sorry, I've moved projects (and employers and type of employment) long ago and haven't done any governmental work in more than two years. I still think it would be a good addition, but I won't be using it anytime soon.

**Comment by idavidmcdonald** [comment]
Thanks :)

For others reading, I know this won't reach very high up our priority list (unless we hear from more users of the client saying this would be useful) and is unlikely that we will action any time soon. We always welcome PRs though if anyone does want to contribute.

**Comment by neilmendum** [comment]
Hi @idavidmcdonald I raised #202 for this
