### ISSUE TITLE
Allow several recipients for email notification

### ISSUE THREAD

**Issue by valydia** [alphagov/notifications-java-client#80]
Currently the API for email only allow to specify one recipient:

`SendEmailResponse response = client.sendEmail(templateId, emailAddress, personalisation, "yourReferenceString", emailReplyToId);`

Could we add / extend this method to support several recipients:

`List<String> emailAddresses = ...`

`SendEmailResponse response = client.sendEmail(templateId, emailAddresses, personalisation, "yourReferenceString", emailReplyToId);`

Where `emailAddresses` is a list of strings.

**Comment by leohemsted** [comment]
Hey @valydia, thanks for the heads-up! We've heard this from a few people, and would need some iteration to ensure we got it right (for example, the `personalisation` field would probably need to be a list at this point too). However, don't think we're planning on doing this soon - there's nothing on our public roadmap about it. https://www.notifications.service.gov.uk/roadmap

For now, I'm afraid you'll have to sort out bulk sending at your end, whether with a simple for loop or some kind of horizontally scalable threaded worker system. Thanks for raising this though! It's good to know what people want in our APIs. 😃

**Comment by valydia** [comment]
@leohemsted Thanks for the reply. We'll use the workaround. Are PR welcomed, or does it need to be first on the roadmap?

**Comment by leohemsted** [comment]
Hey, we typically welcome PRs, however, this would require us to make changes on our API server's end, so wouldn't be appropriate here.
