### ISSUE TITLE
Provide an API endpoint to update programatically an email template

### ISSUE THREAD

**Issue by valydia** [alphagov/notifications-java-client#88]
Currently, as far as I know, we can only update an email template using the User Interface within a web browser. So when we deploy new code to production that requires an email update, we need to remind ourselves to update the email template on Gov Notify. Exposing an endpoint to do that email update, would allow to script that change and to trigger the change as the new code goes live.

**Comment by idavidmcdonald** [comment]
Sorry for the outrageously late comment on this issue but I'm doing some housekeeping.

We don't currently have any plans for this but do keep an eye on our roadmap incase that changes https://www.notifications.service.gov.uk/features/roadmap.

Our best suggestion at the moment is to use a template with the body as a single placeholder, such as `((body))` and then you can control all your content in your version control and have the content go out as part of your deploy. It's not perfect (it means non developers can't go edit the content and you don't get a preview of your content in our web interface) but it is 80% good enough for the moment.

If this is still something important to you then let us know, either on here or you can put in a support request from our website.
